#!/bin/bash
cd ~/nobackup/testing || exit 1
rm -Rf bin
mkdir bin
cp -a /usr/src/cvs/eclipse-workspace/fred/build/main/ bin/
cp -a /usr/src/cvs/eclipse-workspace/fred/build/test/ bin/
echo "Queued requests,Bypass type,Iteration,Requests,Success hops,stddev(success hops),Success rate,stddev(success rate),Inserts failed at least once,Average requests started,Waited for loggable inserts,Request time,Insert time,Running requests overall,Local requests on originator,Average local requests on originator,Requests on originator,average requests on originator" > queued-parallel.csv
SIZE=100
DEGREE=10
HTL=5
ITERATIONS=10
REQUESTS=1000
for PARALLEL in `seq 5 5 150`
do
for ITERATION in `seq $ITERATIONS`; do
BYPASS=NONE
java -cp bin/main/:bin/test/:/usr/src/cvs/eclipse-workspace/fred/lib/freenet/freenet-ext.jar:/usr/src/cvs/eclipse-workspace/fred/lib/bcprov-jdk15on-154.jar freenet.node.simulator.RealNodeParallelLimitedTest parallel-requests=$PARALLEL bypass=$BYPASS total-requests=$REQUESTS size=$SIZE degree=$DEGREE htl=$HTL > log 2>log.err
(echo -n "$PARALLEL,$BYPASS,$ITERATION,$REQUESTS,"; cat log.err | grep -A10 "Requests: $REQUESTS" | tail -n 10 | sed "s/^.*: //;s/ +\\/- /,/" | sed "s/Running requests overall //" | sed "s/Running .*requests on originator //" | sed "s/Inserts failed: //" | sed "s/Waited for loggable inserts: //" | sed "s/Average requests started: //" | sed "s/Average .* time: //" | sed "s/ average /,/" | tr "\n" "," | cut -d "," -f 1-14) >> queued-parallel.csv
done
done
