/**
 * Status messages generated by the node to indicate various problems. Some
 * of these are embedded in various parts of the code, but non-core code
 * should usually use a callback or an exception. Alerts can be rendered in
 * various different ways, and are shown to the user in the hope that (s)he
 * can fix the problem, or in some cases, to tell them that something is so
 * severely broken that Freenet won't work properly.
 */
package freenet.node.useralerts;