name: Google Java Format

on:
  pull_request:
    branches:
      - next  # Update with your main branch name or the branch you want to target

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Update with your desired Java version
          distribution: 'temurin'
    
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Update with Node.js 20 or the desired version

      - name: Install Google Java Format
        run: npm install -g google-java-format

      - name: Run Google Java Format
        run: google-java-format */src*.java

      - name: Create Notification
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = `Hello! Google Java Format has formatted the code in this pull request. Please review the changes.`;
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });
